# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('publicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subject.PublicModel')),
                ('title', models.CharField(default='<无>', max_length=50, verbose_name='阶段标题')),
                ('days', models.IntegerField(verbose_name='学时')),
                ('project', models.CharField(default='<无>', max_length=255, verbose_name='阶段项目')),
                ('teaching', models.CharField(default='<无>', max_length=255, verbose_name='教学方法')),
                ('learning', models.CharField(default='<无>', max_length=255, verbose_name='学习方法')),
                ('sharing', models.CharField(default='<无>', max_length=255, verbose_name='学生分享')),
                ('remark', models.CharField(default='<无>', max_length=255, verbose_name='备注')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectModel')),
            ],
            options={
                'db_table': 'stage',
            },
            bases=('subject.publicmodel',),
        ),
    ]
