# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('outline', '0001_initial'),
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('publicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subject.PublicModel')),
                ('sign', models.CharField(default='<无>', max_length=50, verbose_name='标志性内容')),
                ('digest', models.CharField(default='<无>', max_length=255, verbose_name='内容摘要')),
                ('prepare', models.CharField(default='<无>', max_length=255, verbose_name='准备工作')),
                ('process', models.TextField(default='<无>', max_length=2000, verbose_name='讲课流程')),
                ('attention', models.CharField(default='<无>', max_length=255, verbose_name='注意事项')),
                ('exercise', models.CharField(default='<无>', max_length=255, verbose_name='注意事项')),
                ('share', models.CharField(default='<无>', max_length=255, verbose_name='注意事项')),
                ('management', models.CharField(default='<无>', max_length=255, verbose_name='注意事项')),
                ('remark', models.CharField(default='<无>', max_length=255, verbose_name='注意事项')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.OutlineModel')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.StageModel')),
            ],
            options={
                'db_table': 'program',
            },
            bases=('subject.publicmodel',),
        ),
    ]
