# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('number', models.IntegerField(default=1, verbose_name='顺序')),
                ('creater', models.IntegerField(default=0, verbose_name='创建者id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater', models.IntegerField(default=0, verbose_name='修改者id')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('publicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subject.PublicModel')),
                ('name', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('amount', models.IntegerField(default=0, verbose_name='学费')),
                ('days', models.IntegerField(default=0, verbose_name='学时')),
                ('assurance', models.CharField(default='<无>', max_length=50, verbose_name='承诺')),
                ('remark', models.CharField(default='<无>', max_length=255, verbose_name='备注')),
            ],
            options={
                'db_table': 'subject',
            },
            bases=('subject.publicmodel',),
        ),
    ]
